---
- hosts: all
  gather_facts: yes
  tasks:

  - name: Copy Files From Server A to Server B
    copy:
      src: /path/to/file/server/A
      dest: /path/to/folder/server/B
    delegate_to: 0.0.0.0 # IP Here
